### ISSUE TITLE
Encrypts can’t decrypt binary column?

### ISSUE THREAD

**Issue by emilkarl** [rails/solid_cache#102]
Tried to use encryption on Rails 7.0.2 for my solid cache. Seems like it doesn’t work properly, it encrypts and stores the rows but it can’t be decrypted. It raises exception `ActiveRecord::Encryption::Errors::Decrypt`.

I changed my `value` column to be a `text` and that solves the issue but not sure that is the correct approach? Should it work with the binary column that comes with the default migration? In that case, am I missing some configuration that is not specified in the readme? 🤷‍♂️ 

Using postgresql.

All the best,
Emil

## Working migration
```ruby
class CreateSolidCacheEntries < ActiveRecord::Migration[7.0]
  def change
    create_table :solid_cache_entries do |t|
      t.binary :key, null: false, limit: 1024
      t.text :value, null: false, limit: 512.megabytes
      t.datetime :created_at, null: false

      t.index :key, unique: true
    end
  end
end

```

**Comment by formigarafa** [comment]
That's probably right because the encryption will create a json in which one of the keys is rhe encrypted value.
Of course binary can also hold that string but maybe, if that is supposed to work, there is some type conversion trickery missing or extra.

**Comment by emilkarl** [comment]
Sounds fine. Maybe this should be added to the docs. That if you want to us encrypts your value column have to be a `text` 🤷‍♂️

**Comment by skatkov** [comment]
Haven't taken a deep dive into encryption/decryption code. But it might be, that value needs to unescaped before decrypting.

`PG::Connection.unescape_bytea(value)`
