### ISSUE TITLE
unknown attribute 'key_hash' for SolidCache::Entry. (ActiveModel::UnknownAttributeError)

### ISSUE THREAD

**Issue by ausangshukla** [rails/solid_cache#181]
I just upgraded my Gems, and ruby version to 3.3.3, and have started getting this error

Gemfile.lock
GIT
  remote: https://github.com/ausangshukla/acts_as_favoritor.git
  revision: 353fe5010c225a012cf6d34881827c165eb47281
  specs:
    acts_as_favoritor (6.0.1)
      activerecord (>= 5.0)

GIT
  remote: https://github.com/nejdetkadir/devise-api.git
  revision: 006bddee4bbe9f5ff9edc936d54725ce061be720
  branch: main
  specs:
    devise-api (0.1.3)
      devise (>= 4.7.2)
      dry-configurable (~> 1.0, >= 1.0.1)
      dry-initializer (>= 3.1.1)
      dry-monads (>= 1.6.0)
      dry-types (>= 1.7.0)
      rails (>= 6.0.0)

GIT
  remote: https://github.com/seuros/capistrano-sidekiq.git
  revision: 784b04c973e5c074dc78c30746077c9e6fd2bb9a
  ref: 784b04c973e5c074dc78c30746077c9e6fd2bb9a
  specs:
    capistrano-sidekiq (2.0.0)
      capistrano (>= 3.9.0)
      capistrano-bundler
      sidekiq (>= 6.0)

GIT
  remote: https://github.com/thimmaiah/rupees.git
  revision: db8a7e8b7b4ae6f1728831d38cdb094c18aba30b
  specs:
    rupees (0.1.0)

GIT
  remote: https://github.com/thimmaiah/xirr
  revision: e630a7cbe48dc0d2b6ce49097ca9010643e49ac2
  specs:
    xirr (0.6.1)
      RubyInline (~> 3)
      activesupport (~> 7.0)

GIT
  remote: https://github.com/varvet/pundit.git
  revision: e5f88356c0ad366100b35ae2e3ae7327f8fb9002
  specs:
    pundit (2.3.2)
      activesupport (>= 3.0.0)

GIT
  remote: https://github.com/weshatheleopard/rubyXL.git
  revision: b719e4337a80aa78000bea1a0569cbfeb7783b4f
  specs:
    rubyXL (3.4.27)
      nokogiri (>= 1.10.8)
      rubyzip (>= 1.3.0)

GEM
  remote: https://rubygems.org/
  specs:
    RubyInline (3.14.1)
      ZenTest (~> 4.3)
    ZenTest (4.12.1)
    actioncable (7.1.3.4)
      actionpack (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.1.3.4)
      actionpack (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.1.3.4)
      actionpack (= 7.1.3.4)
      actionview (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.2)
    actionpack (7.1.3.4)
      actionview (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    actiontext (7.1.3.4)
      actionpack (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.1.3.4)
      activesupport (= 7.1.3.4)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    active_flag (1.6.0)
      activerecord (>= 5)
    active_storage_validations (1.1.4)
      activejob (>= 5.2.0)
      activemodel (>= 5.2.0)
      activestorage (>= 5.2.0)
      activesupport (>= 5.2.0)
    activejob (7.1.3.4)
      activesupport (= 7.1.3.4)
      globalid (>= 0.3.6)
    activemodel (7.1.3.4)
      activesupport (= 7.1.3.4)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (7.1.3.4)
      activemodel (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      timeout (>= 0.4.0)
    activerecord-import (1.5.0)
      activerecord (>= 4.2)
    activestorage (7.1.3.4)
      actionpack (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      marcel (~> 1.0)
    activesupport (7.1.3.4)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    acts_as_list (1.2.1)
      activerecord (>= 6.1)
      activesupport (>= 6.1)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    administrate (0.20.1)
      actionpack (>= 6.0, < 8.0)
      actionview (>= 6.0, < 8.0)
      activerecord (>= 6.0, < 8.0)
      jquery-rails (~> 4.6.0)
      kaminari (~> 1.2.2)
      sassc-rails (~> 2.1)
      selectize-rails (~> 0.6)
    administrate-field-active_storage (1.0.3)
      administrate (>= 0.2.2)
      rails (>= 7.0)
    administrate-field-boolean_emoji (0.3.0)
      administrate (< 1.0.0)
      rack (~> 2.0, >= 2.0.8)
      rails (>= 4.2, < 8)
    administrate-field-shrine (0.0.5)
      administrate (> 0.5.0)
      rails (>= 4.2)
    after_commit_action (1.1.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
    airbrussh (1.5.2)
      sshkit (>= 1.6.1, != 1.7.0)
    ajax-datatables-rails (1.5.0)
      rails (>= 6.0)
      zeitwerk
    ancestry (4.3.3)
      activerecord (>= 5.2.6)
    annotate (3.2.0)
      activerecord (>= 3.2, < 8.0)
      rake (>= 10.4, < 14.0)
    ast (2.4.2)
    audited (5.6.0)
      activerecord (>= 5.2, < 7.2)
      activesupport (>= 5.2, < 7.2)
    awesome_print (1.9.2)
    aws-eventstream (1.3.0)
    aws-partitions (1.947.0)
    aws-sdk-core (3.198.0)
      aws-eventstream (~> 1, >= 1.3.0)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.8)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-ec2 (1.462.0)
      aws-sdk-core (~> 3, >= 3.198.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-kms (1.86.0)
      aws-sdk-core (~> 3, >= 3.198.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.153.0)
      aws-sdk-core (~> 3, >= 3.198.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.8)
    aws-sigv4 (1.8.0)
      aws-eventstream (~> 1, >= 1.0.2)
    base64 (0.2.0)
    bcrypt (3.1.20)
    better_errors (2.10.1)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
      rouge (>= 1.0.0)
    better_html (2.1.1)
      actionview (>= 6.0)
      activesupport (>= 6.0)
      ast (~> 2.0)
      erubi (~> 1.4)
      parser (>= 2.4)
      smart_properties
    bigdecimal (3.1.8)
    bindex (0.8.1)
    binding_of_caller (1.0.1)
      debug_inspector (>= 1.2.0)
    blazer (2.6.5)
      activerecord (>= 5)
      chartkick (>= 3.2)
      railties (>= 5)
      safely_block (>= 0.1.1)
    bootsnap (1.15.0)
      msgpack (~> 1.2)
    brakeman (6.1.2)
      racc
    builder (3.3.0)
    bullet (7.1.6)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)
    bundler-audit (0.9.1)
      bundler (>= 1.2.0, < 3)
      thor (~> 1.0)
    byebug (11.1.3)
    capistrano (3.19.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.1.0)
      capistrano (~> 3.1)
    capistrano-rails (1.6.3)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano3-puma (5.2.0)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (>= 4.0, < 6.0)
    capybara (3.40.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.11)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    capybara-email (3.0.2)
      capybara (>= 2.4, < 4.0)
      mail
    caxlsx (4.1.0)
      htmlentities (~> 4.3, >= 4.3.4)
      marcel (~> 1.0)
      nokogiri (~> 1.10, >= 1.10.4)
      rubyzip (>= 1.3.0, < 3)
    caxlsx_rails (0.6.4)
      actionpack (>= 3.1)
      caxlsx (>= 3.0)
    character_set (1.8.0)
    chartkick (5.0.7)
    chewy (7.6.0)
      activesupport (>= 5.2)
      elasticsearch (>= 7.14.0, < 8)
      elasticsearch-dsl
    childprocess (4.1.0)
    chronic (0.10.2)
    client_side_validations (22.2.0)
      js_regex (~> 3.7)
      rails (>= 6.1, < 8.0)
    cocoon (1.2.15)
    code_ownership (1.36.2)
      code_teams (~> 1.0)
      packs-specification
      sorbet-runtime (>= 0.5.11249)
    code_teams (1.0.2)
      sorbet-runtime
    coderay (1.1.3)
    combine_pdf (1.0.26)
      matrix
      ruby-rc4 (>= 0.1.5)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    constant_resolver (0.2.0)
    content_disposition (1.0.0)
    counter_culture (3.7.0)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
    crass (1.0.6)
    csv (3.3.0)
    cucumber (9.2.0)
      builder (~> 3.2)
      cucumber-ci-environment (> 9, < 11)
      cucumber-core (> 13, < 14)
      cucumber-cucumber-expressions (~> 17.0)
      cucumber-gherkin (> 24, < 28)
      cucumber-html-formatter (> 20.3, < 22)
      cucumber-messages (> 19, < 25)
      diff-lcs (~> 1.5)
      mini_mime (~> 1.1)
      multi_test (~> 1.1)
      sys-uname (~> 1.2)
    cucumber-ci-environment (10.0.1)
    cucumber-core (13.0.2)
      cucumber-gherkin (>= 27, < 28)
      cucumber-messages (>= 20, < 23)
      cucumber-tag-expressions (> 5, < 7)
    cucumber-cucumber-expressions (17.1.0)
      bigdecimal
    cucumber-gherkin (27.0.0)
      cucumber-messages (>= 19.1.4, < 23)
    cucumber-html-formatter (21.4.0)
      cucumber-messages (> 19, < 25)
    cucumber-messages (22.0.0)
    cucumber-rails (3.0.0)
      capybara (>= 3.11, < 4)
      cucumber (>= 5, < 10)
      railties (>= 5.2, < 8)
    cucumber-tag-expressions (6.1.0)
    database_cleaner-active_record (2.1.0)
      activerecord (>= 5.a)
      database_cleaner-core (~> 2.0.0)
    database_cleaner-core (2.0.1)
    date (3.3.4)
    debug (1.9.2)
      irb (~> 1.10)
      reline (>= 0.3.8)
    debug_inspector (1.2.0)
    declarative (0.0.20)
    devise (4.9.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.5.1)
    disposable (0.6.3)
      declarative (>= 0.0.9, < 1.0.0)
      representable (>= 3.1.1, < 4)
    docile (1.4.0)
    dotenv (3.1.2)
    dotenv-rails (3.1.2)
      dotenv (= 3.1.2)
      railties (>= 6.1)
    down (5.4.2)
      addressable (~> 2.8)
    draper (4.0.2)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
      activemodel-serializers-xml (>= 1.0)
      activesupport (>= 5.0)
      request_store (>= 1.0)
      ruby2_keywords
    drb (2.2.1)
    dry-configurable (1.1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-core (1.0.1)
      concurrent-ruby (~> 1.0)
      zeitwerk (~> 2.6)
    dry-inflector (1.0.0)
    dry-initializer (3.1.1)
    dry-logic (1.5.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-monads (1.6.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0, < 2)
      zeitwerk (~> 2.6)
    dry-types (1.7.2)
      bigdecimal (~> 3.0)
      concurrent-ruby (~> 1.0)
      dry-core (~> 1.0)
      dry-inflector (~> 1.0)
      dry-logic (~> 1.4)
      zeitwerk (~> 2.6)
    elasticsearch (7.17.11)
      elasticsearch-api (= 7.17.11)
      elasticsearch-transport (= 7.17.11)
    elasticsearch-api (7.17.11)
      multi_json
    elasticsearch-dsl (0.1.10)
    elasticsearch-transport (7.17.11)
      base64
      faraday (>= 1, < 3)
      multi_json
    enumerize (2.8.1)
      activesupport (>= 3.2)
    erubi (1.13.0)
    erubis (2.7.0)
    et-orbi (1.2.11)
      tzinfo
    eu_central_bank (1.7.0)
      money (~> 6.13, >= 6.13.6)
      nokogiri (~> 1.9)
    event_stream_parser (1.0.0)
    exception_notification (4.5.0)
      actionmailer (>= 5.2, < 8)
      activesupport (>= 5.2, < 8)
    factory_bot (6.4.6)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.4.3)
      factory_bot (~> 6.4)
      railties (>= 5.0.0)
    faker (3.4.1)
      i18n (>= 1.8.11, < 2)
    faraday (2.9.2)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (3.1.0)
      net-http
    ffi (1.17.0-x86_64-linux-gnu)
    foreman (0.88.1)
    friendly_id (5.5.1)
      activerecord (>= 4.0.0)
    fugit (1.11.0)
      et-orbi (~> 1, >= 1.2.11)
      raabro (~> 1.4)
    globalid (1.2.1)
      activesupport (>= 6.1)
    groupdate (6.4.0)
      activesupport (>= 6.1)
    has_scope (0.8.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
    hashie (5.0.0)
    hightop (0.4.0)
      activesupport (>= 6.1)
    hirb (0.7.3)
    htmlbeautifier (1.4.3)
    htmlentities (4.3.4)
    httparty (0.22.0)
      csv
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    image_processing (1.12.2)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    importmap-rails (2.0.1)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    iniparse (1.5.0)
    io-console (0.7.2)
    irb (1.13.2)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.12.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    jquery-rails (4.6.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    js_regex (3.11.1)
      character_set (~> 1.4)
      regexp_parser (>= 2.6.2, < 3.0.0)
      regexp_property_values (~> 1.0)
    json (2.7.2)
    json2table (1.0.7)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    language_server-protocol (3.17.0.3)
    launchy (2.5.2)
      addressable (~> 2.8)
    letter_opener (1.10.0)
      launchy (>= 2.2, < 4)
    libreconv (0.9.5)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    mail-logger (0.0.4)
      mail
    marcel (1.0.4)
    marginalia (1.11.1)
      actionpack (>= 5.2)
      activerecord (>= 5.2)
    matrix (0.4.2)
    memoized (1.1.1)
    method_source (1.1.0)
    mini_magick (4.13.1)
    mini_mime (1.1.5)
    minitest (5.24.0)
    monetize (1.13.0)
      money (~> 6.12)
    money (6.19.0)
      i18n (>= 0.6.4, <= 2)
    money-rails (1.15.0)
      activesupport (>= 3.0)
      monetize (~> 1.9)
      money (~> 6.13)
      railties (>= 3.0)
    msgpack (1.7.2)
    multi_json (1.15.0)
    multi_test (1.1.0)
    multi_xml (0.7.1)
      bigdecimal (~> 3.1)
    multipart-post (2.4.1)
    mutex_m (0.2.0)
    mysql2 (0.5.6)
    net-http (0.4.1)
      uri
    net-imap (0.4.14)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-scp (4.0.0)
      net-ssh (>= 2.6.5, < 8.0.0)
    net-sftp (4.0.0)
      net-ssh (>= 5.0.0, < 8.0.0)
    net-smtp (0.5.0)
      net-protocol
    net-ssh (7.2.3)
    nio4r (2.7.3)
    nokogiri (1.16.6-x86_64-linux)
      racc (~> 1.4)
    noticed (2.3.3)
      rails (>= 6.1.0)
    orm_adapter (0.5.0)
    overcommit (0.58.0)
      childprocess (>= 0.6.3, < 5)
      iniparse (~> 1.4)
      rexml (~> 3.2)
    packs (0.0.44)
      bigdecimal
      code_ownership (>= 1.33.0)
      packs-specification
      packwerk
      parse_packwerk (>= 0.25.0)
      rainbow
      sorbet-runtime
      thor
      tty-prompt
    packs-rails (0.0.5)
      activesupport
      packs
      railties
    packs-specification (0.0.10)
      sorbet-runtime
    packwerk (3.2.1)
      activesupport (>= 6.0)
      ast
      better_html
      bundler
      constant_resolver (>= 0.2.0)
      parallel
      parser
      prism (>= 0.25.0)
      sorbet-runtime (>= 0.5.9914)
      zeitwerk (>= 2.6.1)
    parallel (1.25.1)
    paranoia (2.6.3)
      activerecord (>= 5.1, < 7.2)
    parse_packwerk (0.25.0)
      bigdecimal
      sorbet-runtime
    parser (3.3.3.0)
      ast (~> 2.4.1)
      racc
    pastel (0.8.0)
      tty-color (~> 0.5)
    prism (0.30.0)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-byebug (3.10.1)
      byebug (~> 11.0)
      pry (>= 0.13, < 0.15)
    psych (5.1.2)
      stringio
    public_suffix (6.0.0)
    puma (5.6.8)
      nio4r (~> 2.0)
    raabro (1.4.0)
    racc (1.8.0)
    rack (2.2.9)
    rack-attack (6.7.0)
      rack (>= 1.0, < 4)
    rack-session (1.0.2)
      rack (< 3)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (1.0.0)
      rack (< 3)
      webrick
    rails (7.1.3.4)
      actioncable (= 7.1.3.4)
      actionmailbox (= 7.1.3.4)
      actionmailer (= 7.1.3.4)
      actionpack (= 7.1.3.4)
      actiontext (= 7.1.3.4)
      actionview (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activemodel (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      bundler (>= 1.15.0)
      railties (= 7.1.3.4)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.1.3.4)
      actionpack (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rainbow (3.1.1)
    rake (13.2.1)
    ransack (4.1.1)
      activerecord (>= 6.1.5)
      activesupport (>= 6.1.5)
      i18n
    rdoc (6.7.0)
      psych (>= 4.0.0)
    redis (4.8.1)
    redis-client (0.22.2)
      connection_pool
    reform (2.6.2)
      disposable (>= 0.5.0, < 1.0.0)
      representable (>= 3.1.1, < 4)
      uber (< 0.2.0)
    regexp_parser (2.9.2)
    regexp_property_values (1.5.2)
    reline (0.5.9)
      io-console (~> 0.5)
    representable (3.2.0)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    request_store (1.7.0)
      rack (>= 1.4)
    responders (3.1.1)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.3.1)
      strscan
    roda (3.81.0)
      rack
    rolify (6.0.1)
    roo (2.10.1)
      nokogiri (~> 1)
      rubyzip (>= 1.3.0, < 3.0.0)
    rouge (4.3.0)
    rspec-core (3.13.0)
      rspec-support (~> 3.13.0)
    rspec-expectations (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-rails (6.1.3)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.13)
      rspec-expectations (~> 3.13)
      rspec-mocks (~> 3.13)
      rspec-support (~> 3.13)
    rspec-support (3.13.1)
    rswag-api (2.13.0)
      activesupport (>= 3.1, < 7.2)
      railties (>= 3.1, < 7.2)
    rswag-ui (2.13.0)
      actionpack (>= 3.1, < 7.2)
      railties (>= 3.1, < 7.2)
    rubocop (1.64.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.31.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.31.3)
      parser (>= 3.3.1.0)
    rubocop-performance (1.21.1)
      rubocop (>= 1.48.1, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rails (2.25.0)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
      rubocop-ast (>= 1.31.1, < 2.0)
    rubocop-rspec (3.0.1)
      rubocop (~> 1.61)
    ruby-ole (1.2.13.1)
    ruby-openai (7.1.0)
      event_stream_parser (>= 0.3.0, < 2.0.0)
      faraday (>= 1)
      faraday-multipart (>= 1)
    ruby-progressbar (1.13.0)
    ruby-rc4 (0.1.5)
    ruby-vips (2.2.1)
      ffi (~> 1.12)
    ruby2_keywords (0.0.5)
    ruby_http_client (3.5.5)
    rubyzip (2.3.2)
    rufus-scheduler (3.9.1)
      fugit (~> 1.1, >= 1.1.6)
    sablon (0.4.0)
      nokogiri (>= 1.8.5)
      rubyzip (>= 1.3.0)
    safely_block (0.4.0)
    sanitize_email (2.0.7)
      mail (~> 2.0)
      version_gem (~> 1.1, >= 1.1.4)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    scout_apm (5.3.8)
      parser
    selectize-rails (0.12.6)
    selenium-webdriver (4.10.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sendgrid-ruby (6.7.0)
      ruby_http_client (~> 3.4)
    shrine (3.6.0)
      content_disposition (~> 1.0)
      down (~> 5.1)
    sidekiq (7.2.4)
      concurrent-ruby (< 2)
      connection_pool (>= 2.3.0)
      rack (>= 2.2.4)
      redis-client (>= 0.19.0)
    sidekiq-scheduler (5.0.3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 6, < 8)
      tilt (>= 1.4.0)
    simplecov (0.22.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.4)
    smart_properties (1.17.0)
    solid_cache (0.6.0)
      activejob (>= 7)
      activerecord (>= 7)
      railties (>= 7)
    sorbet-runtime (0.5.11444)
    spreadsheet (1.3.1)
      bigdecimal
      ruby-ole
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.5.1)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      sprockets (>= 3.0.0)
    sshkit (1.23.0)
      base64
      net-scp (>= 1.1.2)
      net-sftp (>= 2.1.2)
      net-ssh (>= 2.8.0)
    stimulus-rails (1.3.3)
      railties (>= 6.0.0)
    stringio (3.1.1)
    strscan (3.1.0)
    sys-uname (1.3.0)
      ffi (~> 1.1)
    thor (1.3.1)
    tilt (2.3.0)
    timeout (0.4.1)
    to_words (1.1.1)
    trailblazer (2.1.3)
      trailblazer-activity-dsl-linear (>= 1.2.3, < 1.3.0)
      trailblazer-developer (>= 0.1.0, < 0.2.0)
      trailblazer-macro (>= 2.1.15, < 2.2.0)
      trailblazer-macro-contract (>= 2.1.4, < 2.2.0)
      trailblazer-operation (>= 0.9.0, < 1.0.0)
    trailblazer-activity (0.16.2)
      trailblazer-context (~> 0.5.0)
      trailblazer-option (~> 0.1.0)
    trailblazer-activity-dsl-linear (1.2.5)
      trailblazer-activity (>= 0.16.0, < 0.17.0)
      trailblazer-declarative (>= 0.0.1, < 0.1.0)
    trailblazer-context (0.5.1)
      hashie (>= 3.0.0)
    trailblazer-declarative (0.0.2)
    trailblazer-developer (0.1.0)
      hirb
      trailblazer-activity-dsl-linear (>= 1.2.0, < 1.3.0)
    trailblazer-macro (2.1.15)
      trailblazer-activity-dsl-linear (>= 1.2.0, < 1.3.0)
      trailblazer-operation (>= 0.10.1)
    trailblazer-macro-contract (2.1.5)
      reform (>= 2.2.0, < 3.0.0)
      trailblazer-activity-dsl-linear (>= 1.2.0, < 1.3.0)
    trailblazer-operation (0.10.1)
      trailblazer-activity-dsl-linear (>= 1.2.0, < 1.4.0)
      trailblazer-developer (>= 0.1.0, < 0.2.0)
    trailblazer-option (0.1.2)
    tty-color (0.6.0)
    tty-cursor (0.7.1)
    tty-prompt (0.23.1)
      pastel (~> 0.8)
      tty-reader (~> 0.8)
    tty-reader (0.9.0)
      tty-cursor (~> 0.7)
      tty-screen (~> 0.8)
      wisper (~> 2.0)
    tty-screen (0.8.2)
    turbo-rails (2.0.5)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    unicode-display_width (2.5.0)
    uniform_notifier (1.16.0)
    uppy-s3_multipart (1.2.1)
      aws-sdk-s3 (~> 1.0)
      content_disposition (~> 1.0)
      roda (>= 2.27, < 4)
    uri (0.13.0)
    version_gem (1.1.4)
    view_component (3.12.1)
      activesupport (>= 5.2.0, < 8.0)
      concurrent-ruby (~> 1.0)
      method_source (~> 1.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.3.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0, < 4.11)
    webrick (1.8.1)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    wisper (2.0.1)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yajl-ruby (1.4.3)
    zeitwerk (2.6.16)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  active_flag
  active_storage_validations
  activerecord-import (= 1.5.0)
  acts_as_favoritor!
  acts_as_list
  administrate
  administrate-field-active_storage
  administrate-field-boolean_emoji
  administrate-field-shrine
  after_commit_action
  ajax-datatables-rails
  ancestry
  annotate
  audited (~> 5.0)
  awesome_print
  aws-sdk-ec2
  aws-sdk-s3
  better_errors
  binding_of_caller
  blazer (~> 2.6)
  bootsnap (= 1.15.0)
  brakeman
  bullet
  bundler-audit
  capistrano (~> 3.5)
  capistrano-bundler (~> 2.0)
  capistrano-rails
  capistrano-rvm
  capistrano-sidekiq!
  capistrano3-puma
  capybara
  capybara-email
  caxlsx
  caxlsx_rails
  chartkick
  chewy
  client_side_validations
  cocoon
  combine_pdf
  counter_culture
  cucumber-rails
  database_cleaner-active_record
  debug
  devise
  devise-api!
  dotenv-rails
  draper
  enumerize
  erubis
  eu_central_bank
  exception_notification
  factory_bot_rails
  faker
  foreman
  friendly_id (~> 5.5.0)
  groupdate
  has_scope
  hightop
  htmlbeautifier
  httparty
  image_processing (~> 1.2)
  importmap-rails
  jbuilder
  json2table
  kaminari
  letter_opener
  libreconv
  mail-logger
  marginalia (~> 1.11)
  memoized
  money-rails (~> 1.12)
  mysql2 (~> 0.5)
  net-ssh
  noticed
  overcommit (~> 0.58.0)
  packs-rails
  paranoia
  pry-byebug
  puma (~> 5.0)
  pundit!
  rack-attack
  rails (= 7.1.3.4)
  ransack
  redis (~> 4.0)
  rolify
  roo
  rspec-rails
  rswag-api
  rswag-ui
  rubocop-performance
  rubocop-rails
  rubocop-rspec
  ruby-openai
  rubyXL!
  rubyzip
  rupees!
  sablon
  sanitize_email
  sassc-rails
  scout_apm
  selenium-webdriver
  sendgrid-ruby
  shrine (~> 3.3)
  sidekiq
  sidekiq-scheduler
  simplecov
  solid_cache (= 0.6.0)
  spreadsheet
  sprockets-rails
  stimulus-rails
  to_words
  trailblazer
  turbo-rails
  tzinfo-data
  uppy-s3_multipart (~> 1.1)
  view_component
  web-console
  webdrivers
  whenever
  xirr!
  yajl-ruby

BUNDLED WITH
   2.3.12

**Comment by ausangshukla** [comment]
Downgrading to  0.4.2, removed this error

**Comment by djmb** [comment]
Hi @ausangshukla - there are migrations you will need to run - you can find the upgrade steps here - https://github.com/rails/solid_cache/blob/main/upgrading_to_version_0.4.x.md
