### ISSUE TITLE
Support for write with `unless_exist: true` 

### ISSUE THREAD

**Issue by mintuhouse** [rails/solid_cache#183]
I am implementing a simple lock interface on Rails.cache 
& currently using `Rails.cache.fetch(lock_key, expires_in: timeout) { lock_value } == lock_value`
But it is not atomic as it makes multiple SQL queries

Can we implement support for `Rails.cache.write(lock_key, lock_value, unless_exist: true, expires_in: timeout)`

**Comment by djmb** [comment]
Should be fixed by https://github.com/rails/solid_cache/pull/188, but that will have to wait for support for Rails 7.1 and earlier to be dropped.

**Comment by skatkov** [comment]
@djmb can we have two side-by-side? 

In case Rails 7.1 unless_exist version will be used, if version is older it will use different class.

**Comment by djmb** [comment]
@skatkov - I've had to rework the PR to handle expired entries, which had the side effect of removing the dependency on Rails 7.2+ so we'll be able to merge that now.
