### ISSUE TITLE
How do you manage fragment caching invalidation?

### ISSUE THREAD

**Issue by guillaumebriday** [rails/solid_cache#245]
Hey! 👋 

This one’s probably a question for @djmb or @dhh at Basecamp. 😊

I use fragment caching quite a bit, but I often run into issues when the cached content includes helpers, translations (like date formats or text), etc. Here’s an example:

```erb
<%# app/views/comments/index.html.erb %>
<%= render partial: 'comments/comment', collection: @comments, cached: true %>

<%# app/views/comments/_comment.html.erb %>
<%= t('comments.title') %>
<%= badge_tag(@comment.status) %>

<%= t(comment.created_at, format: :long) %>

<div class="prose">
  <%= comment.content %>
</div>
```

If the output of a helper or translation changes, the cache isn’t invalidated unless the associated data (like the `comments`) is updated.

The Rails docs suggest adding comments to adjust the MD5 hash for cache keys, but that seems really hard to maintain: https://guides.rubyonrails.org/caching_with_rails.html#external-dependencies.

When I used Redis, the cache size was so small that it frequently invalidated itself. But now, with Solid Cache, it doesn’t.

In your video (https://www.youtube.com/watch?v=wYeVne3aRow), you mentioned using a background job to invalidate caches, but I’m unclear on how you handle this process overall.

I guess we could also configure SolidCache with a `max_age` that matches our deployment frequency, https://github.com/rails/solid_cache?tab=readme-ov-file#configuration, I don't know..

How do you manage this?

**Comment by dhh** [comment]
Do all such translations using JavaScript. Like the local-time gem does.
